### ISSUE TITLE
Database Integration

### ISSUE THREAD

**Issue by etblink** [etblink/Backend-Hive-API#2]
### Description
Replace in-memory storage with a persistent database.

### Tasks
- [ ] Choose a database (SQLite, PostgreSQL, MongoDB)
- [ ] Migrate existing data models to database schema
- [ ] Update API endpoints to use database
