### ISSUE TITLE
Subscription Management System

### ISSUE THREAD

**Issue by etblink** [etblink/Backend-Hive-API#5]
### Description
Implement a subscription system where users pay for accessing custom frontend API, and direct these fees to the DHF.

### Tasks
- [ ] Design subscription model
- [ ] Implement payment processing
- [ ] Ensure subscription fees are directed to DHF
- [ ] Test subscription flow
