### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by etblink** [etblink/Backend-Hive-API#6]
### Description
Create comprehensive API documentation using Swagger or Postman.

### Tasks
- [ ] Set up Swagger or Postman documentation
- [ ] Document all API endpoints
- [ ] Include examples and usage instructions
- [ ] Update documentation regularly
