### ISSUE TITLE
Develop Sample Frontend

### ISSUE THREAD

**Issue by etblink** [etblink/Backend-Hive-API#7]
### Description
Develop a sample frontend to demonstrate how to use the API.

### Tasks
- [ ] Choose a frontend framework (React, Vue, Angular)
- [ ] Design UI/UX
- [ ] Implement sample frontend features
- [ ] Integrate with backend API
- [ ] Test sample frontend
